# Generated by Django 3.2.5 on 2021-07-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име на Компанията')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Имейл Адрес')),
                ('phone_1', models.CharField(default='+359 8 ', max_length=20, verbose_name='Основен Телефон за Контакт')),
                ('phone_2', models.CharField(max_length=20, null=True, verbose_name='Допълнителен телефон за контакт')),
                ('cover_back', models.ImageField(blank=True, help_text='Моля, изберете снимка', null=True, upload_to='runners_images/', verbose_name='Лого на компанията')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_type', models.PositiveSmallIntegerField(choices=[(1, 'Взимане от собственик'), (2, 'Доставяне до собственик'), (3, 'Взимане от ХЪБ'), (4, 'Доставяне до ХЪБ'), (5, 'Взимане от междинно звено'), (6, 'Доставяне до междинно звено')])),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('ts_pickup', models.DateTimeField(null=True)),
                ('ts_delivery', models.DateTimeField(null=True)),
                ('delivery_rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('runner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_runners.runnercompany')),
            ],
        ),
    ]
