# Generated by Django 3.2.5 on 2021-08-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_runners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runnercompany',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='runnerlog',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterField(
            model_name='runnercompany',
            name='phone_1',
            field=models.CharField(default='+359 8', max_length=20, verbose_name='Основен Телефон за Контакт'),
        ),
        migrations.AlterField(
            model_name='runnercompany',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Допълнителен телефон за контакт'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='delivery_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Рейтинг на поръчката'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='from_place',
            field=models.CharField(max_length=100, verbose_name='от позиция'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='runner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_runners.runnercompany', verbose_name='Име на компанията'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='to_place',
            field=models.CharField(max_length=100, verbose_name='до позиция'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='transportation_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Взимане от собственик'), (2, 'Доставяне до собственик'), (3, 'Взимане от ХЪБ'), (4, 'Доставяне до ХЪБ'), (5, 'Взимане от междинно звено'), (6, 'Доставяне до междинно звено')], verbose_name='Тип транспорт'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='ts_delivery',
            field=models.DateTimeField(null=True, verbose_name='Дата / час'),
        ),
        migrations.AlterField(
            model_name='runnerlog',
            name='ts_pickup',
            field=models.DateTimeField(null=True, verbose_name='Дата / час'),
        ),
    ]
