# Generated by Django 3.2.5 on 2021-07-14 13:01

import booktopia.books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, unique=True, verbose_name='Име')),
                ('last_name', models.CharField(max_length=25, unique=True, verbose_name='Фамилия')),
                ('pseudonym', models.CharField(max_length=25, null=True, unique=True, verbose_name='Псевдоним')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Рожденна Дата')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Починал на')),
                ('nationality', models.CharField(max_length=25, null=True, verbose_name='Националност')),
                ('wiki_page', models.URLField(blank=True, max_length=150, null=True, verbose_name='Страница в Уикипедиа или Биография')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване на записа')),
                ('user_id_num', models.IntegerField(default=0)),
                ('book_id_num', models.IntegerField(blank=True, unique=True)),
                ('comment', models.TextField(null=True, verbose_name='Съдържание на кометара')),
                ('up_votes_count', models.PositiveSmallIntegerField(default=0)),
                ('down_votes_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментари',
            },
        ),
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Име')),
                ('address', models.TextField(blank=True, verbose_name='Пощенски адрес')),
                ('country', models.CharField(choices=[('AL', 'Албания'), ('DZ', 'Алжир'), ('AD', 'Андора'), ('AR', 'Аржентина'), ('AM', 'Армения'), ('AU', 'Австралия'), ('AT', 'Австрия'), ('BY', 'Беларус'), ('BE', 'Белгия'), ('BO', 'Боливия'), ('BA', 'Босна и Херцеговина'), ('BR', 'Бразилия'), ('BG', 'България'), ('KH', 'Камбоджа'), ('CM', 'Камерун'), ('CA', 'Канада'), ('IC', 'Канарски острови'), ('TD', 'Чад'), ('CL', 'Чили'), ('CN', 'Китай'), ('CO', 'Колумбия'), ('CG', 'Конго'), ('CD', 'Конго, Демократична Република'), ('CR', 'Коста Рика'), ('CI', "Кот д'Ивоар"), ('HR', 'Хърватия'), ('CY', 'Кипър'), ('CZ', 'Чехия'), ('DK', 'Дания'), ('EC', 'Египет'), ('TL', 'Еквадор'), ('EN', 'Англия'), ('ER', 'Еритрея'), ('EE', 'Естония'), ('ET', 'Етиопия'), ('FJ', 'Фиджи'), ('FI', 'Финландия'), ('FR', 'Франция'), ('GA', 'Габон'), ('GM', 'Гамбия'), ('GE', 'Грузия'), ('DE', 'Германия'), ('GH', 'Гана'), ('GI', 'Гибралтар'), ('GR', 'Гърция'), ('GD', 'Гренада'), ('GP', 'Гваделупа'), ('GY', 'Гвиана'), ('HT', 'Хаити'), ('NL', 'Холандия'), ('HK', 'Хонконг'), ('HU', 'Унгария'), ('IS', 'Исландия'), ('IN', 'Индия'), ('ID', 'Индонезия'), ('IQ', 'Ирак'), ('IL', 'Израел'), ('IT', 'Италия'), ('JM', 'Ямайка'), ('JP', 'Япония'), ('JO', 'Йордания'), ('KZ', 'Казахстан'), ('KE', 'Кения'), ('KW', 'Кувейт'), ('KG', 'Киргизстан'), ('LA', 'Лаос'), ('LV', 'Латвия'), ('LB', 'Ливан'), ('LS', 'Лесото'), ('LR', 'Либерия'), ('LI', 'Лихтенщайн'), ('LU', 'Люксембург'), ('MO', 'Макао'), ('MK', 'Северна Македония'), ('MG', 'Мадагаскар'), ('MY', 'Малайзия'), ('ML', 'Мали'), ('MT', 'Малта'), ('MQ', 'Мартиника'), ('MX', 'Мексико'), ('MD', 'Молдова'), ('MC', 'Монако'), ('MN', 'Монголия'), ('ME', 'Черна гора'), ('MA', 'Мароко'), ('MZ', 'Мозамбик'), ('NA', 'Намибия'), ('NP', 'Непал'), ('NL', 'Холандия'), ('NC', 'Нова Каледония'), ('NZ', 'НоваЗеландия'), ('NI', 'Никарагуа'), ('NE', 'Нигер'), ('NG', 'Нигерия'), ('NB', 'Северна Ирландия'), ('NO', 'Норвегия'), ('OM', 'Оман'), ('PK', 'Пакистан'), ('PA', 'Панама'), ('PG', 'Папуа Нова Гвинея'), ('PY', 'Парагвай'), ('PE', 'Перу'), ('PH', 'Филипини'), ('PL', 'Полша'), ('PT', 'Португалия'), ('PR', 'ПуертоРико'), ('QA', 'Катар'), ('CG', 'Република Конго'), ('IE', 'Република Ирландия'), ('YE', 'Република Йемен'), ('RO', 'Румъния'), ('RU', 'Русия'), ('RW', 'Руанда'), ('WS', 'Самоа'), ('SM', 'Сан Марино'), ('SA', 'Саудитска Арабия'), ('GB', 'Шотландия'), ('SN', 'Сенегал'), ('RS', 'Сърбия'), ('SG', 'Сингапур'), ('SK', 'Словакия'), ('SI', 'Словения'), ('SB', 'Соломонови острови'), ('ZA', 'Южна Африка'), ('KR', 'Южна Корея'), ('ES', 'Испания'), ('LK', 'Шри Ланка'), ('AN', 'Сен Бартелми'), ('KN', 'Сейнт Кристофър'), ('SE', 'Швеция'), ('CH', 'Швейцария'), ('PF', 'Таити'), ('TW', 'Тайван'), ('TJ', 'Таджикистан'), ('TZ', 'Танзания'), ('TH', 'Тайланд'), ('MP', 'Тиниан'), ('TG', 'Того'), ('TO', 'Тонга'), ('VG', 'Тортола'), ('TT', 'Тринидад и Тобаго'), ('TN', 'Тунис'), ('TR', 'Турция'), ('TM', 'Туркменистан'), ('UG', 'Уганда'), ('UA', 'Украйна'), ('AE', 'Обединени Арабски Емирства'), ('GB', 'Обединеното кралство'), ('US', 'САЩ'), ('UY', 'Уругвай'), ('UZ', 'Узбекистан'), ('VA', 'Ватикана'), ('VE', 'Венецуела'), ('VN', 'Виетнам'), ('GB', 'Уелс'), ('ZM', 'Замбия'), ('ZW', 'Зимбабве')], max_length=100, verbose_name='Държава')),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('stars', models.PositiveSmallIntegerField(default=0, null=True)),
                ('web_address', models.URLField(blank=True, max_length=150, null=True, verbose_name='Уеб Сайт')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
            ],
            options={
                'verbose_name': 'Издателство',
                'verbose_name_plural': 'Издателства',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_from', models.DateTimeField(auto_created=True)),
                ('timestamp_to', models.DateField()),
                ('by_user', models.IntegerField()),
                ('rent_event_comment', models.TextField()),
                ('degradations', models.TextField()),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата-час')),
                ('user_id', models.PositiveIntegerField()),
                ('book_id', models.PositiveIntegerField(default=0)),
                ('review', models.TextField(null=True, verbose_name='Съдържание на ревюто')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Ревю',
                'verbose_name_plural': 'Ревюта',
            },
        ),
        migrations.CreateModel(
            name='TransportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transportation_type', models.PositiveSmallIntegerField(choices=[(1, 'Взимане от собственик'), (2, 'Доставяне до собственик'), (3, 'Взимане от ХЪБ'), (4, 'Доставяне до ХЪБ'), (5, 'Взимане от междинно звено'), (6, 'Доставяне до междинно звено')])),
                ('runner_id', models.PositiveIntegerField()),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('event_comment', models.TextField()),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име на книгата')),
                ('series', models.CharField(blank=True, max_length=100, null=True, verbose_name='Поредица')),
                ('translated', models.BooleanField(default=False, verbose_name='Преведена')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='Оригинално име')),
                ('edition_lang', models.CharField(blank=True, choices=[(1, 'Български език'), (2, 'Английски език'), (3, 'Френски език'), (4, 'Испански език'), (5, 'Немски език'), (6, 'Румънски език'), (7, 'Руски език'), (8, 'Турски език'), (9, 'Ирландски език'), (10, 'Исландски език'), (11, 'Италиански език'), (12, 'Шведски език'), (13, 'Датски език'), (14, 'Унгарски език'), (15, 'Чешки език'), (16, 'Естонски език'), (17, 'Сръбски език'), (18, 'Словашки език'), (19, 'Словенски език'), (20, 'Полски език'), (21, 'Португалски език'), (22, 'Гръцки език'), (23, 'Латински език'), (24, 'Беларуски език'), (27, 'Албански език'), (29, 'Арабски език'), (30, 'Арменски език'), (46, 'Иврит'), (57, 'Корейски език'), (60, 'Латвийски език'), (61, 'Литовски език'), (62, 'Люксембургски език'), (67, 'Малтийски език'), (72, 'Молдовски език'), (105, 'Украински език'), (110, 'Фински език'), (112, 'Хинди'), (114, 'Холандски език'), (115, 'Хърватски език'), (117, 'Японски език')], max_length=3, verbose_name='Език на изданието')),
                ('edition_lang_orig', models.CharField(blank=True, choices=[(1, 'Български език'), (2, 'Английски език'), (3, 'Френски език'), (4, 'Испански език'), (5, 'Немски език'), (6, 'Румънски език'), (7, 'Руски език'), (8, 'Турски език'), (9, 'Ирландски език'), (10, 'Исландски език'), (11, 'Италиански език'), (12, 'Шведски език'), (13, 'Датски език'), (14, 'Унгарски език'), (15, 'Чешки език'), (16, 'Естонски език'), (17, 'Сръбски език'), (18, 'Словашки език'), (19, 'Словенски език'), (20, 'Полски език'), (21, 'Португалски език'), (22, 'Гръцки език'), (23, 'Латински език'), (24, 'Беларуски език'), (27, 'Албански език'), (29, 'Арабски език'), (30, 'Арменски език'), (46, 'Иврит'), (57, 'Корейски език'), (60, 'Латвийски език'), (61, 'Литовски език'), (62, 'Люксембургски език'), (67, 'Малтийски език'), (72, 'Молдовски език'), (105, 'Украински език'), (110, 'Фински език'), (112, 'Хинди'), (114, 'Холандски език'), (115, 'Хърватски език'), (117, 'Японски език')], max_length=3, verbose_name='Оригинален Език')),
                ('book_current_status', models.CharField(choices=[('F', 'СВОБОДНА'), ('R', 'ЗАЕТА'), ('TR', 'ПЪТУВАЩА'), ('WR', 'ИЗЧАКВАЩА ПОЛУЧАВАНЕ ОТ ЧИТАТЕЛ'), ('WO', 'ИЗЧАКВАЩА ПОЛУЧАВАНЕ ОТ СОБСТВЕНИК'), ('S', 'ПРОДАДЕНА'), ('BR', 'БРАКУВАНА'), ('L', 'ЗАГУБЕНА')], default='F', max_length=25, verbose_name='Актуално състояние на книгата')),
                ('catalog_num', models.CharField(blank=True, default=None, help_text='Каталожен номер по десетична система. Полето е задължително', max_length=100, null=True, verbose_name='Вътрешен каталожен номер')),
                ('isbn_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='ISBN')),
                ('oclc_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='OCLC')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Синопсис')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Бележка')),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Година на изданието')),
                ('release_number', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Първо'), (2, 'Второ'), (3, 'Трето'), (4, 'Четвърто'), (5, 'Пето'), (9, 'БЕЗ')], default=1, help_text='Поредно Издание', null=True, verbose_name='Издание')),
                ('pages_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Брой Страници')),
                ('measure_x', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ширина (cм)')),
                ('measure_y', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Височина (cм)')),
                ('weight_grams', models.PositiveSmallIntegerField(blank=True, default=250, verbose_name='Тегло Грама')),
                ('visual_condition', models.PositiveSmallIntegerField(choices=[(1, 'Отлично'), (2, 'Добро'), (3, 'Лошо')], default=1, null=True, verbose_name='Състояние')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрита')),
                ('book_reserved', models.BooleanField(default=False, verbose_name='Резервирана')),
                ('book_to_read_by_owner', models.BooleanField(default=False, verbose_name='Непрочетена')),
                ('price_for_rent', models.FloatField(default=0, verbose_name='Стойност на гаранцията (лв.)')),
                ('price_for_sell', models.FloatField(blank=True, null=True, verbose_name='Цена за продажба (лв.)')),
                ('has_been_rented_times', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Заемана пъти')),
                ('cover_front', models.ImageField(blank=True, help_text='Verif de la path', null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Корица')),
                ('cover_back', models.ImageField(blank=True, help_text='Verif de la path back', null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Гръб')),
                ('generated_qr_code_image', models.ImageField(blank=True, null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Автоматичен QR Код')),
                ('generated_qr_code_content', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='books.author', verbose_name='Автор(и)')),
                ('book_comments', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='books.comments', verbose_name='Коментари')),
                ('book_rent_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='books.renthistory', verbose_name='История на заеманията')),
                ('book_reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.reviews', verbose_name='Ревюта')),
                ('book_transportation_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='books.transporthistory', verbose_name='История на транспортиранията')),
                ('editions', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='books.editions', verbose_name='Издателска къща')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='book_owners.owner', verbose_name='Собственик')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('name',),
            },
        ),
    ]
