# Generated by Django 3.2.5 on 2021-07-14 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='record_updated_at',
        ),
        migrations.RemoveField(
            model_name='editions',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='editions',
            name='record_updated_at',
        ),
        migrations.RemoveField(
            model_name='renthistory',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='renthistory',
            name='record_updated_at',
        ),
        migrations.RemoveField(
            model_name='transporthistory',
            name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='transporthistory',
            name='record_updated_at',
        ),
        migrations.AddField(
            model_name='author',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване на записа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване на записа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renthistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване на записа'),
            preserve_default=False,
        ),
    ]
