# Generated by Django 3.2.5 on 2021-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='rent_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'ПЛАНИРАНА'), ('EFFECTIVE', 'ТЕКУЩА'), ('TERMINATED', 'ПРИКЛЮЧИЛА'), ('UNATTRACTIVE', 'БЕЗ ПРОДЪЛЖЕНИЕ')], default='NULL', max_length=12, null=True),
        ),
    ]
