# Generated by Django 3.2.5 on 2021-08-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_renthistory_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_reviews',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
