# Generated by Django 3.2.5 on 2021-07-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_owners', '0001_initial'),
        ('books', '0002_auto_20210714_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.comments', verbose_name='Коментари'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_owners.owner', verbose_name='Собственик'),
        ),
    ]
