# Generated by Django 3.2.5 on 2021-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210714_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='Обявена за продажба'),
        ),
    ]
