# Generated by Django 3.2.5 on 2021-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editions',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='editions',
            name='record_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа'),
        ),
        migrations.AddField(
            model_name='editions',
            name='record_updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа'),
        ),
    ]
