# Generated by Django 3.2.5 on 2021-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210810_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editions',
            name='logo',
            field=models.ImageField(blank=True, upload_to='editions_images/', verbose_name='Лого'),
        ),
        migrations.AlterField(
            model_name='editions',
            name='stars',
            field=models.PositiveSmallIntegerField(default=5, null=True, verbose_name='Звезди'),
        ),
    ]
