# Generated by Django 3.2.5 on 2021-07-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210718_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransportHistory',
            new_name='StatusHistory',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_current_status',
            field=models.CharField(choices=[('F', 'СВОБОДНА'), ('R', 'ЗАЕТА'), ('WR', 'ИЗЧАКВАЩА ПОЛУЧАВАНЕ ОТ ЧИТАТЕЛ'), ('WO', 'ИЗЧАКВАЩА ПОЛУЧАВАНЕ ОТ СОБСТВЕНИК'), ('S', 'ПРОДАДЕНА'), ('L', 'ЗАГУБЕНА')], default='F', max_length=25, verbose_name='Актуално състояние на книгата'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Не показвай в Booktopia (скрита)'),
        ),
    ]
