# Generated by Django 3.2.5 on 2021-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210718_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_type', models.PositiveSmallIntegerField(choices=[(1, 'Взимане от собственик'), (2, 'Доставяне до собственик'), (3, 'Взимане от ХЪБ'), (4, 'Доставяне до ХЪБ'), (5, 'Взимане от междинно звено'), (6, 'Доставяне до междинно звено')])),
                ('runner_id', models.PositiveIntegerField()),
                ('from_place', models.CharField(max_length=100)),
                ('to_place', models.CharField(max_length=100)),
                ('event_comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='event_comment',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='runner_id',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='to_place',
        ),
        migrations.RemoveField(
            model_name='statushistory',
            name='transportation_type',
        ),
    ]
