# Generated by Django 3.2.5 on 2021-07-19 13:52

import booktopia.books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210718_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RunnerHistory',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_back',
            field=models.ImageField(blank=True, help_text='Моля, изберете снимка', null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Гръб'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_front',
            field=models.ImageField(blank=True, help_text='Моля, изберете снимка', null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Корица'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_for_rent',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1.0, message='Минималната гараранция е 1,00 лев.')], verbose_name='Стойност на гаранцията (лв.)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_for_sell',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.2, message='Минималната цена е 1,20 лева.')], verbose_name='Цена за продажба (лв.)'),
        ),
    ]
