# Generated by Django 3.2.5 on 2021-08-02 14:03

import booktopia.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210729_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_back',
            field=models.ImageField(blank=True, default='/static/generic/generic-book-2.png', null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Гръб'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_front',
            field=models.ImageField(blank=True, default='/static/generic/generic-book-2.png', null=True, upload_to=booktopia.books.models.Book.file_upload_path, verbose_name='Корица'),
        ),
    ]
