# Generated by Django 3.2.5 on 2021-08-02 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0015_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_reviews',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='book_id_num',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id_num',
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.booktopiauser'),
            preserve_default=False,
        ),
    ]
