# Generated by Django 3.2.5 on 2021-08-02 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210802_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.reviews', verbose_name='Ревюта'),
        ),
    ]
