# Generated by Django 3.2.5 on 2021-08-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_book_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_comments',
        ),
    ]
