# Generated by Django 3.2.5 on 2021-08-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_book_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='book_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
            preserve_default=False,
        ),
    ]
