# Generated by Django 3.2.5 on 2021-08-03 15:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('books', '0019_comments_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тагове, разделени със запетайка'),
        ),
    ]
