# Generated by Django 3.2.5 on 2021-08-14 07:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.booktopiauser')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Име')),
                ('middle_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Презиме')),
                ('family_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия')),
                ('gender', models.CharField(blank=True, choices=[('M', 'МЪЖ'), ('F', 'ЖЕНА'), ('O', 'ДРУГ')], max_length=10, null=True, verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата на раждане')),
                ('egn_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Единен граждански номер')),
                ('region_of_birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='Роден в област')),
                ('astrological_sign', models.CharField(blank=True, max_length=20, null=True, verbose_name='Зодиакален знак')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+359|0)[ ]\\s?8(\\d{2}\\s\\d{3}[-]\\d{3}|[789]\\d{7})$', message='Невалиден телефонен номер')], verbose_name='Мобилен телефон във формат +359 888 123-456 или 0 888 123-456')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_owners', verbose_name='Снимка или аватар')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
            ],
            options={
                'verbose_name': 'Потребителски Акаунт',
                'verbose_name_plural': 'Потребителски Акаунти',
                'ordering': ['first_name'],
            },
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата на създаване на акаунта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='is_runner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booktopiauser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Последено влизане на потребителя'),
            preserve_default=False,
        ),
    ]
