# Generated by Django 3.2.5 on 2021-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booktopiauser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktopiauser',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Дата на промяна на записа'),
        ),
        migrations.AlterField(
            model_name='booktopiauser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата на последено влизане на потребителя'),
        ),
    ]
