# Generated by Django 3.2.5 on 2021-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210720_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktopiauser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата на промяна на записа'),
        ),
    ]
