# Generated by Django 3.2.5 on 2021-07-20 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_booktopiauser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktopiauser',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата на промяна на записа'),
        ),
    ]
