# Generated by Django 3.2.5 on 2021-07-20 18:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210720_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktopiauser',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='is_runner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booktopiauser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booktopiauser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване на акаунта'),
        ),
        migrations.AlterField(
            model_name='booktopiauser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Последено влизане на потребителя'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Име')),
                ('middle_name', models.CharField(blank=True, max_length=25, verbose_name='Презиме')),
                ('family_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'МЪЖ'), ('F', 'ЖЕНА'), ('O', 'ДРУГ')], max_length=1, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата на раждане')),
                ('mobile_phone', models.CharField(max_length=20, unique=True, verbose_name='Мобилен текефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_owners', verbose_name='Снимка или аватар')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Потребителски Акаунт',
                'verbose_name_plural': 'Потребителски Акаунти',
                'ordering': ['first_name'],
            },
        ),
    ]
