# Generated by Django 3.2.5 on 2021-08-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210804_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='egn_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Единен граждански номер'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, default='+359 8', max_length=20, null=True, unique=True, verbose_name='Мобилен телефон'),
        ),
    ]
