# Generated by Django 3.2.5 on 2021-08-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210805_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='astrological_sign',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Зодиакален знак'),
        ),
        migrations.AddField(
            model_name='profile',
            name='region_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Роден в област'),
        ),
    ]
