# Generated by Django 3.2.5 on 2021-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210806_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, default='+359 8', max_length=20, null=True, verbose_name='Мобилен телефон'),
        ),
    ]
