# Generated by Django 3.2.5 on 2021-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Име'),
        ),
    ]
