# Generated by Django 3.2.5 on 2021-08-12 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210810_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+359|0)[ ]\\s?8(\\d{2}\\s\\d{3}[-]\\d{3}|[789]\\d{7})$', message='Невалиден телефонен номер')], verbose_name='Мобилен телефон във формат +359 888 123-456 или 0 888 123-456'),
        ),
    ]
