# Generated by Django 3.2.5 on 2021-08-14 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Име')),
                ('middle_name', models.CharField(blank=True, max_length=25, verbose_name='Презиме')),
                ('family_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'МЪЖ'), ('F', 'ЖЕНА'), ('O', 'ДРУГ')], max_length=1, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата на раждане')),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Имейл адрес')),
                ('mobile_phone', models.CharField(max_length=20, unique=True, verbose_name='Мобилен текефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_owners', verbose_name='Снимка или аватар')),
                ('record_created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата на създаване на записа')),
                ('record_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата на промяна на записа')),
            ],
            options={
                'verbose_name': 'Собственик',
                'verbose_name_plural': 'Собственици',
                'ordering': ['first_name'],
            },
        ),
    ]
