# Generated by Django 3.2.5 on 2021-07-20 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Имейл адрес'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='family_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mobile_phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Мобилен текефон'),
        ),
    ]
